name: safe_chat
description: A secure way to chat

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.1
  get: ^4.6.5
  get_it:
  overlay_support:
  font_awesome_flutter:
  dio:
  hive:
  hive_flutter:
  flutter_screenutil:
  stacked:
  carousel_slider:
  connectivity:
  provider:
  jwt_decode:
  image_picker:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/png/
    - assets/images/jpg/
    - assets/images/svg/